SRL_A:
  90:
    - 20190711_0139_biBTSP_SRL_A_90cm_cell1_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190719_0320_biBTSP_SRL_A_90cm_cell11_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190719_0333_biBTSP_SRL_A_90cm_cell28_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190720_0058_biBTSP_SRL_A_90cm_cell29_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190720_0108_biBTSP_SRL_A_90cm_cell30_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190720_0453_biBTSP_SRL_A_90cm_cell8_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190720_0453_biBTSP_SRL_A_90cm_cell31_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190720_1406_biBTSP_SRL_A_90cm_cell15_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190720_1414_biBTSP_SRL_A_90cm_cell18_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190721_0006_biBTSP_SRL_A_90cm_cell4_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190721_0056_biBTSP_SRL_A_90cm_cell5_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190721_2322_biBTSP_SRL_A_90cm_cell7_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190721_2322_biBTSP_SRL_A_90cm_cell9_PopulationAnnealing_optimization_exported_output.hdf5
SRL_B:
  90:
    - 20190711_1905_biBTSP_SRL_B_90cm_cell1_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190723_0008_biBTSP_SRL_B_90cm_cell11_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190723_0013_biBTSP_SRL_B_90cm_cell28_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190723_1347_biBTSP_SRL_B_90cm_cell29_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190723_1600_biBTSP_SRL_B_90cm_cell30_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190724_1853_biBTSP_SRL_B_90cm_cell31_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190724_1954_biBTSP_SRL_B_90cm_cell8_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190725_1329_biBTSP_SRL_B_90cm_cell15_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190725_1432_biBTSP_SRL_B_90cm_cell18_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190725_1621_biBTSP_SRL_B_90cm_cell4_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190725_1829_biBTSP_SRL_B_90cm_cell5_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190725_2005_biBTSP_SRL_B_90cm_cell9_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190802_2118_biBTSP_SRL_B_90cm_cell7_PopulationAnnealing_optimization_exported_output.hdf5
  75:
    - 20190801_0252_biBTSP_SRL_B_75cm_cell11_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0636_biBTSP_SRL_B_75cm_cell29_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0650_biBTSP_SRL_B_75cm_cell30_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0709_biBTSP_SRL_B_75cm_cell31_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0715_biBTSP_SRL_B_75cm_cell8_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0747_biBTSP_SRL_B_75cm_cell15_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0841_biBTSP_SRL_B_75cm_cell18_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0844_biBTSP_SRL_B_75cm_cell9_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0850_biBTSP_SRL_B_75cm_cell5_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0850_biBTSP_SRL_B_75cm_cell7_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0857_biBTSP_SRL_B_75cm_cell4_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190811_1854_biBTSP_SRL_B_75cm_cell1_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190811_2029_biBTSP_SRL_B_75cm_cell28_PopulationAnnealing_optimization_exported_output.hdf5
  105:
    - 20190724_0805_biBTSP_SRL_B_105cm_cell28_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190725_1648_biBTSP_SRL_B_105cm_cell29_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0833_biBTSP_SRL_B_105cm_cell11_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0843_biBTSP_SRL_B_105cm_cell31_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0854_biBTSP_SRL_B_105cm_cell30_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0902_biBTSP_SRL_B_105cm_cell8_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0945_biBTSP_SRL_B_105cm_cell18_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_1008_biBTSP_SRL_B_105cm_cell7_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_1014_biBTSP_SRL_B_105cm_cell15_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_1025_biBTSP_SRL_B_105cm_cell4_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_1054_biBTSP_SRL_B_105cm_cell9_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190802_2201_biBTSP_SRL_B_105cm_cell5_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190811_2029_biBTSP_SRL_B_105cm_cell1_PopulationAnnealing_optimization_exported_output.hdf5
SRL_C:
  90:
    - 20190711_1905_biBTSP_SRL_C_90cm_cell1_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190725_2024_biBTSP_SRL_C_90cm_cell11_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190725_2054_biBTSP_SRL_C_90cm_cell28_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190725_2136_biBTSP_SRL_C_90cm_cell29_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190725_2136_biBTSP_SRL_C_90cm_cell30_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190725_2216_biBTSP_SRL_C_90cm_cell31_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0230_biBTSP_SRL_C_90cm_cell18_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0253_biBTSP_SRL_C_90cm_cell15_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0314_biBTSP_SRL_C_90cm_cell8_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0449_biBTSP_SRL_C_90cm_cell4_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0507_biBTSP_SRL_C_90cm_cell5_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0509_biBTSP_SRL_C_90cm_cell7_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0609_biBTSP_SRL_C_90cm_cell9_PopulationAnnealing_optimization_exported_output.hdf5
VD_A:
  90:
    - 20190713_0014_biBTSP_VD_A_90cm_cell1_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_0847_biBTSP_VD_A_90cm_cell11_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_1033_biBTSP_VD_A_90cm_cell28_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_1110_biBTSP_VD_A_90cm_cell29_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190801_1119_biBTSP_VD_A_90cm_cell30_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190802_0507_biBTSP_VD_A_90cm_cell15_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190802_0524_biBTSP_VD_A_90cm_cell18_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190802_1625_biBTSP_VD_A_90cm_cell4_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190802_1741_biBTSP_VD_A_90cm_cell5_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190803_0102_biBTSP_VD_A_90cm_cell7_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190803_0210_biBTSP_VD_A_90cm_cell9_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190811_2029_biBTSP_VD_A_90cm_cell8_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190811_2029_biBTSP_VD_A_90cm_cell31_PopulationAnnealing_optimization_exported_output.hdf5
VD_B:
  90:
    - 20190713_0014_biBTSP_VD_B_90cm_cell1_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190802_0144_biBTSP_VD_B_90cm_cell11_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190802_1913_biBTSP_VD_B_90cm_cell28_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190802_1914_biBTSP_VD_B_90cm_cell29_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190802_1919_biBTSP_VD_B_90cm_cell30_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190802_2200_biBTSP_VD_B_90cm_cell8_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190802_2201_biBTSP_VD_B_90cm_cell15_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190802_2201_biBTSP_VD_B_90cm_cell18_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190802_2201_biBTSP_VD_B_90cm_cell31_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190803_0109_biBTSP_VD_B_90cm_cell4_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190803_0459_biBTSP_VD_B_90cm_cell5_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190803_0632_biBTSP_VD_B_90cm_cell7_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190803_0649_biBTSP_VD_B_90cm_cell9_PopulationAnnealing_optimization_exported_output.hdf5
VD_C:
  90:
    - 20190713_0014_biBTSP_VD_C_90cm_cell1_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190725_0347_biBTSP_VD_C_90cm_cell11_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190803_0625_biBTSP_VD_C_90cm_cell28_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190803_0626_biBTSP_VD_C_90cm_cell29_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190803_1407_biBTSP_VD_C_90cm_cell30_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190803_1407_biBTSP_VD_C_90cm_cell31_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190803_1411_biBTSP_VD_C_90cm_cell8_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190803_1456_biBTSP_VD_C_90cm_cell4_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190803_1456_biBTSP_VD_C_90cm_cell15_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190804_1811_biBTSP_VD_C_90cm_cell18_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190804_1924_biBTSP_VD_C_90cm_cell5_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190812_2004_biBTSP_VD_C_90cm_cell7_PopulationAnnealing_optimization_exported_output.hdf5
    - 20190812_2016_biBTSP_VD_C_90cm_cell9_PopulationAnnealing_optimization_exported_output.hdf5
