bounds:
  vd_peak: !!python/tuple
  - 0.001
  - 100.
  vd_th_pot: !!python/tuple
  - -40.
  - 15.
  vd_th_dep: !!python/tuple
  - -40.
  - 15.
  vd_min: !!python/tuple
  - 0.
  - 1.
  f_pot_peak: !!python/tuple
  - 0.001
  - 1.
  f_pot_th: !!python/tuple
  - 0.001
  - 1.
  f_dep_th: !!python/tuple
  - 0.001
  - 1.
  f_dep_peak: !!python/tuple
  - 0.001
  - 1.
  k_pot: !!python/tuple
  - 0.01
  - 10.
  k_dep: !!python/tuple
  - 0.01
  - 10.
  local_signal_rise: !!python/tuple
  - 5.
  - 200.
  local_signal_decay: !!python/tuple
  - 50.
  - 2500.
  global_signal_rise: !!python/tuple
  - 5.
  - 200.
  global_signal_decay: !!python/tuple
  - 50.
  - 2500.
  peak_delta_weight: !!python/tuple
  - 1.5
  - 4.
default_params:
  peak_delta_weight: 2.5
  vd_min: 0.
rel_bounds:
- - local_signal_decay
  - '>'
  - 1.0
  - local_signal_rise
- - global_signal_decay
  - '>'
  - 1.0
  - global_signal_rise
- - local_signal_decay
  - '>'
  - 1.0
  - global_signal_decay
- - k_pot
  - '>'
  - 1.0
  - k_dep
feature_names:
- induction1_delta_val_at_target_peak
- induction1_delta_val_at_model_peak
- induction1_delta_width
- induction1_delta_peak_shift
- induction1_delta_asymmetry
- induction1_delta_min_loc
- induction1_delta_val_at_target_min
- induction1_delta_val_at_model_min
- induction1_depo_delta_val_at_target_peak
- induction1_depo_delta_val_at_model_peak
- induction1_depo_delta_width
- induction1_depo_delta_peak_shift
- induction1_depo_delta_asymmetry
- induction1_depo_delta_min_loc
- induction1_depo_delta_val_at_target_min
- induction1_depo_delta_val_at_model_min
- induction1_hyper_delta_val_at_target_peak
- induction1_hyper_delta_val_at_model_peak
- induction1_hyper_delta_width
- induction1_hyper_delta_peak_shift
- induction1_hyper_delta_asymmetry
- induction1_hyper_delta_min_loc
- induction1_hyper_delta_val_at_target_min
- induction1_hyper_delta_val_at_model_min
- induction2_delta_val_at_target_peak
- induction2_delta_val_at_model_peak
- induction2_delta_width
- induction2_delta_peak_shift
- induction2_delta_asymmetry
- induction2_delta_min_loc
- induction2_delta_val_at_target_min
- induction2_delta_val_at_model_min
- induction2_hyper_delta_val_at_target_peak
- induction2_hyper_delta_val_at_model_peak
- induction2_hyper_delta_width
- induction2_hyper_delta_peak_shift
- induction2_hyper_delta_asymmetry
- induction2_hyper_delta_min_loc
- induction2_hyper_delta_val_at_target_min
- induction2_hyper_delta_val_at_model_min
- ramp_amp_after_first_plateau
update_context:
- - optimize_biBTSP_synthetic_hybrid
  - update_model_params
get_features_stages:
- source: optimize_biBTSP_synthetic_hybrid
  get_args_static: get_args_static_model_ramp
  compute_features: compute_features_model_ramp
  filter_features: filter_features_model_ramp
get_objectives:
  optimize_biBTSP_synthetic_hybrid: get_objectives
kwargs:
  data_file_name: 20190711_biBTSP_data_calibrated_input.hdf5
  input_field_width: 90.  # cm
  verbose: 1
  min_delta_weight: -0.2
  min_delta_ramp: -60.
  plateau_delta_vm: 15.
  peak_delta_ramp: 25.
  default_run_vel: 25.
  induction_loc:
    '1': 120.
    '2': 45.
  target_peak_delta_weight: 3.
  target_peak_shift_1: -10.
  target_peak_shift_2: 0.
  target_peak_val_1: 8.
  target_peak_val_1_depo: 12.
  target_peak_val_2: 8.
  target_min_val_2: 4.
  target_ramp_offset_1_depo: 10.
  target_ramp_offset_1_hyper: -40.
  target_ramp_offset_2_hyper: -25.
objective_names:
- induction1_residual_score
- induction1_depo_residual_score
- induction1_hyper_residual_score
- induction2_residual_score
- induction2_hyper_residual_score
- self_consistent_delta_residual_score
optimization_title: biBTSP_synthetic_hybrid
param_gen: PopulationAnnealing
param_names:
- vd_peak
- vd_th_pot
- vd_th_dep
- vd_min
- f_pot_peak
- f_pot_th
- f_dep_th
- f_dep_peak
- k_pot
- k_dep
- local_signal_rise
- local_signal_decay
- global_signal_rise
- global_signal_decay
- peak_delta_weight
target_range:
  ramp_offset: 0.01
  delta_min_val: 0.01
  delta_peak_val: 0.01
  residuals: 0.1
  weights_smoothness: 0.005
  ramp_amp_after_first_plateau: 0.01
target_val:
  ramp_amp_after_first_plateau: 5.
x0:
  f_dep_peak: 8.036030E-03
  f_dep_th: 2.855647E-02
  f_pot_peak: 7.600603E-01
  f_pot_th: 1.385298E-01
  global_signal_decay: 3.570670E+02
  global_signal_rise: 3.555186E+01
  k_dep: 3.126094E-01
  k_pot: 2.280166E+00
  local_signal_decay: 1.191872E+03
  local_signal_rise: 1.939650E+02
  peak_delta_ramp: 15.
  peak_delta_weight: 2.
  vd_min: 0.
  vd_peak: 10.
  vd_th_pot: 0.
  vd_th_dep: -40.
