bounds:
  rMC_peak: !!python/tuple
  - 0.001
  - 1.
  rMC_th: !!python/tuple
  - 0.001
  - 1.
  rCM_th: !!python/tuple
  - 0.001
  - 1.
  rCM_peak: !!python/tuple
  - 0.001
  - 1.
  rMC0: !!python/tuple
  - 0.01
  - 10.
  rCM0: !!python/tuple
  - 0.01
  - 10.
  pot_signal_rise: !!python/tuple
  - 5.
  - 200.
  pot_signal_decay: !!python/tuple
  - 50.
  - 2500.
  depot_signal_rise: !!python/tuple
  - 5.
  - 200.
  depot_signal_decay: !!python/tuple
  - 50.
  - 2500.
  global_signal_rise: !!python/tuple
  - 5.
  - 200.
  global_signal_decay: !!python/tuple
  - 50.
  - 2500.
  peak_delta_weight: !!python/tuple
  - 1.5
  - 4.
default_params:
rel_bounds:
- - pot_signal_decay
  - '>'
  - 1.0
  - pot_signal_rise
- - depot_signal_decay
  - '>'
  - 1.0
  - depot_signal_rise
- - global_signal_decay
  - '>'
  - 1.0
  - global_signal_rise
- - pot_signal_decay
  - '>'
  - 1.0
  - global_signal_decay
- - depot_signal_decay
  - '>'
  - 1.0
  - pot_signal_decay
- - rMC0
  - '>'
  - 1.0
  - rCM0
feature_names:
- spont_delta_amp
- spont_delta_width
- spont_delta_peak_shift
- spont_delta_asymmetry
- spont_delta_min_loc
- spont_delta_min_val
- exp1_delta_amp
- exp1_delta_width
- exp1_delta_peak_shift
- exp1_delta_asymmetry
- exp1_delta_min_loc
- exp1_delta_min_val
- exp2_delta_amp
- exp2_delta_width
- exp2_delta_peak_shift
- exp2_delta_asymmetry
- exp2_delta_min_loc
- exp2_delta_min_val
update_context:
- - optimize_biBTSP_F
  - update_model_params
get_features_stages:
- source: optimize_biBTSP_F
  get_args_static: get_args_static_signal_amplitudes
  compute_features: compute_features_signal_amplitudes
  filter_features: filter_features_signal_amplitudes
- source: optimize_biBTSP_F
  get_args_dynamic: get_args_dynamic_model_ramp
  compute_features: compute_features_model_ramp
  filter_features: filter_features_model_ramp
get_objectives:
  optimize_biBTSP_F: get_objectives
kwargs:
  data_file_name: 20190621_biBTSP_data_calibrated_input.hdf5
  input_field_width: 45.  # cm
  verbose: 1
  min_delta_weight: -0.2
  params_path: config/20190625_biBTSP_F_90cm_initial_params.yaml
objective_names:
- spont_residual_score
- exp1_residual_score
- exp2_residual_score
- self_consistent_delta_residual_score
optimization_title: biBTSP_F_45cm
param_gen: PopulationAnnealing
param_names:
- rMC_peak
- rMC_th
- rCM_th
- rCM_peak
- rMC0
- rCM0
- pot_signal_rise
- pot_signal_decay
- depot_signal_rise
- depot_signal_decay
- global_signal_rise
- global_signal_decay
- peak_delta_weight
target_range:
  ramp_offset: 0.01
  delta_min_val: 0.01
  delta_peak_val: 0.01
  residuals: 0.1
  weights_smoothness: 0.01
target_val:
x0:
  global_signal_decay: 327.9013424874619
  global_signal_rise: 33.10370285112559
  peak_delta_weight: 3.8584356046894137
  rCM0: 0.27166095889790975
  rCM_peak: 0.00447680672223396
  rCM_th: 0.0015410493348019167
  rMC0: 1.0627627534180737
  rMC_peak: 0.20959879679896984
  rMC_th: 0.1836517377352108
  pot_signal_rise: 8.55238892503821
  pot_signal_decay: 917.3782517534474
  depot_signal_rise: 8.55238892503821
  depot_signal_decay: 917.3792517534475