bounds:
  k_pot: !!python/tuple
  - 0.1
  - 10.
  k_dep: !!python/tuple
  - 0.1
  - 10.
  f_pot_th: !!python/tuple
  - 0.001
  - 1.
  f_pot_half_width: !!python/tuple
  - 0.001
  - 1.
  f_dep_th: !!python/tuple
  - 0.001
  - 1.
  f_dep_half_width: !!python/tuple
  - 0.001
  - 1.
  local_signal_decay: !!python/tuple
  - 50.
  - 1500.
  global_signal_decay: !!python/tuple
  - 50.
  - 1500.
  peak_delta_ramp: !!python/tuple
  - 15.
  - 40.
rel_bounds:
- - local_signal_decay
  - '>'
  - 1.0
  - global_signal_decay
- - k_pot
  - '>'
  - 1.0
  - k_dep
feature_names:
- spont_delta_val_at_target_peak
- spont_delta_val_at_model_peak
- spont_delta_width
- spont_delta_peak_shift
- spont_delta_asymmetry
- spont_delta_min_loc
- spont_delta_val_at_target_min
- spont_delta_val_at_model_min
- exp1_delta_val_at_target_peak
- exp1_delta_val_at_model_peak
- exp1_delta_width
- exp1_delta_peak_shift
- exp1_delta_asymmetry
- exp1_delta_min_loc
- exp1_delta_val_at_target_min
- exp1_delta_val_at_model_min
- exp2_delta_val_at_target_peak
- exp2_delta_val_at_model_peak
- exp2_delta_width
- exp2_delta_peak_shift
- exp2_delta_asymmetry
- exp2_delta_min_loc
- exp2_delta_val_at_target_min
- exp2_delta_val_at_model_min
update_context:
- - optimize_biBTSP_VD_D
  - update_model_params
get_features_stages:
- source: optimize_biBTSP_VD_D
  get_args_static: get_args_static_signal_amplitudes
  compute_features: compute_features_signal_amplitudes
  filter_features: filter_features_signal_amplitudes
- source: optimize_biBTSP_VD_D
  get_args_dynamic: get_args_dynamic_model_ramp
  compute_features: compute_features_model_ramp
  filter_features: filter_features_model_ramp
get_objectives:
  optimize_biBTSP_VD_D: get_objectives
kwargs:
  data_file_name: 20190711_biBTSP_data_calibrated_input.hdf5
  input_field_width: 90.  # cm
  verbose: 1
  min_delta_weight: -0.2
objective_names:
- spont_residual_score
- exp1_residual_score
- exp2_residual_score
- self_consistent_delta_residual_score
optimization_title: biBTSP_VD_D
param_gen: PopulationAnnealing
param_names:
- k_pot
- k_dep
- f_pot_th
- f_pot_half_width
- f_dep_th
- f_dep_half_width
- local_signal_decay
- global_signal_decay
- peak_delta_ramp
target_range:
  ramp_offset: 0.01
  delta_min_val: 0.01
  delta_peak_val: 0.01
  residuals: 0.1
  weights_smoothness: 0.005
target_val:
x0:
  peak_delta_ramp: 15.
  global_signal_decay: 5.117370E+02
  k_dep: 2.577449E-01
  k_pot: 2.691966E+00
  local_signal_decay: 1.5E+03
  f_dep_half_width: 1.526457E-03
  f_dep_th: 1.000023E-03
  f_pot_half_width: 3.882245E-02
  f_pot_th: 1.593557E-01
