bounds:
  f_dep_th: !!python/tuple
  - 0.00001
  - 1.
  f_dep_half_width: !!python/tuple
  - 0.00004
  - 1.
  k_pot: !!python/tuple
  - 0.001
  - 10.
  k_dep: !!python/tuple
  - 0.001
  - 10.
  local_signal_decay: !!python/tuple
  - 50.
  - 1750.
  global_signal_decay: !!python/tuple
  - 50.
  - 1750.
  peak_delta_weight: !!python/tuple
  - 1.5
  - 4.
default_params:
rel_bounds:
#- - local_signal_decay
#  - '>'
#  - 1.0
#  - global_signal_decay
#- - k_pot
#  - '>'
#  - 1.0
#  - k_dep
feature_names:
- spont_delta_val_at_target_peak
- spont_delta_val_at_model_peak
- spont_delta_width
- spont_delta_peak_shift
- spont_delta_asymmetry
- spont_delta_min_loc
- spont_delta_val_at_target_min
- spont_delta_val_at_model_min
- exp1_delta_val_at_target_peak
- exp1_delta_val_at_model_peak
- exp1_delta_width
- exp1_delta_peak_shift
- exp1_delta_asymmetry
- exp1_delta_min_loc
- exp1_delta_val_at_target_min
- exp1_delta_val_at_model_min
- exp2_delta_val_at_target_peak
- exp2_delta_val_at_model_peak
- exp2_delta_width
- exp2_delta_peak_shift
- exp2_delta_asymmetry
- exp2_delta_min_loc
- exp2_delta_val_at_target_min
- exp2_delta_val_at_model_min
- exp3_delta_val_at_target_peak
- exp3_delta_val_at_model_peak
- exp3_delta_width
- exp3_delta_peak_shift
- exp3_delta_asymmetry
- exp3_delta_min_loc
- exp3_delta_val_at_target_min
- exp3_delta_val_at_model_min
update_context:
- - optimize_biBTSP_WD_F
  - update_model_params
get_features_stages:
- source: optimize_biBTSP_WD_F
  get_args_static: get_args_static_signal_amplitudes
  compute_features: compute_features_signal_amplitudes
  filter_features: filter_features_signal_amplitudes
- source: optimize_biBTSP_WD_F
  get_args_dynamic: get_args_dynamic_model_ramp
  compute_features: compute_features_model_ramp
  filter_features: filter_features_model_ramp
get_objectives:
  optimize_biBTSP_WD_F: get_objectives
kwargs:
  data_file_name: 20201123_biBTSP_data.hdf5
  input_field_width: 90.  # cm
  verbose: 1
  min_delta_weight: -0.2
  weights_path_distance_threshold: 2.
objective_names:
- spont_residual_score
- exp1_residual_score
- exp2_residual_score
- exp3_residual_score
- weights_path_distance
optimization_title: biBTSP_WD_F
param_gen: PopulationAnnealing
param_names:
- f_dep_th
- f_dep_half_width
- k_pot
- k_dep
- local_signal_decay
- global_signal_decay
- peak_delta_weight
target_range:
  ramp_offset: 0.01
  delta_min_val: 0.01
  delta_peak_val: 0.01
  residuals: 0.1
  weights_smoothness: 0.015
  weights_path_distance: 0.1
target_val:
x0:
  f_dep_half_width: 1.829962E-04
  f_dep_th: 1.032972E-04
  global_signal_decay: 4.163098E+02
  k_dep: 5.776883E-02
  k_pot: 8.506520E+00
  local_signal_decay: 5.784831E+02
  peak_delta_weight: 2.125376E+00
