bounds:
  k_pot: !!python/tuple
  - 0.1
  - 10.
  k_depot: !!python/tuple
  - 0.1
  - 10.
  r_pot_th: !!python/tuple
  - 0.001
  - 1.
  r_pot_peak: !!python/tuple
  - 0.001
  - 1.
  r_depot_th: !!python/tuple
  - 0.001
  - 1.
  r_depot_peak: !!python/tuple
  - 0.001
  - 1.
  local_signal_rise: !!python/tuple
  - 5.
  - 200.
  local_signal_decay: !!python/tuple
  - 50.
  - 2500.
  global_signal_rise: !!python/tuple
  - 5.
  - 200.
  global_signal_decay: !!python/tuple
  - 50.
  - 2500.
  delta_peak_ramp_amp: !!python/tuple
  - 0.
  - 10.
rel_bounds:
- - local_signal_decay
  - '>'
  - 1.0
  - local_signal_rise
- - global_signal_decay
  - '>'
  - 1.0
  - global_signal_rise
- - local_signal_decay
  - '>'
  - 1.0
  - global_signal_decay
- - k_pot
  - '>'
  - 1.0
  - k_depot
feature_names:
- spont_delta_amp
- spont_delta_width
- spont_delta_peak_shift
- spont_delta_asymmetry
- spont_delta_min_loc
- spont_delta_min_val
- exp1_delta_amp
- exp1_delta_width
- exp1_delta_peak_shift
- exp1_delta_asymmetry
- exp1_delta_min_loc
- exp1_delta_min_val
- exp2_delta_amp
- exp2_delta_width
- exp2_delta_peak_shift
- exp2_delta_asymmetry
- exp2_delta_min_loc
- exp2_delta_min_val
update_context:
- - optimize_biBTSP_V_B
  - update_model_params
get_features_stages:
- source: optimize_biBTSP_V_B
  get_args_static: get_args_static_signal_amplitudes
  compute_features: compute_features_signal_amplitudes
  filter_features: filter_features_signal_amplitudes
- source: optimize_biBTSP_V_B
  get_args_dynamic: get_args_dynamic_model_ramp
  compute_features: compute_features_model_ramp
  filter_features: filter_features_model_ramp
get_objectives:
  optimize_biBTSP_V_B: get_objectives
kwargs:
  data_file_name: 20190621_biBTSP_data_calibrated_input.hdf5
  input_field_width: 90.  # cm
  verbose: 1
  min_delta_weight: -0.2
  # params_path: config/20180511_best_params.yaml
objective_names:
- spont_residual_score
- exp1_residual_score
- exp2_residual_score
- self_consistent_delta_residual_score
optimization_title: biBTSP_V_B_90cm
param_gen: PopulationAnnealing
param_names:
- k_pot
- k_depot
- r_pot_th
- r_pot_peak
- r_depot_th
- r_depot_peak
- local_signal_rise
- local_signal_decay
- global_signal_rise
- global_signal_decay
- delta_peak_ramp_amp
target_range:
  ramp_offset: 0.01
  delta_min_val: 0.01
  delta_peak_val: 0.01
  residuals: 0.1
  weights_smoothness: 0.01
target_val:
x0:
  k_pot: 9.991864E+00
  k_depot: 1.030430E-01
  local_signal_rise: 1.995811E+02
  local_signal_decay: 4.546595E+02
  global_signal_rise: 1.199720E+02
  global_signal_decay: 2.566589E+02
  delta_peak_ramp_amp: 0.
  r_pot_th: 3.160245E-01
  r_pot_peak: 4.092345E-01
  r_depot_th: 7.109480E-02
  r_depot_peak: 7.443065E-01
