bounds:
  rMC_peak: !!python/tuple
  - 0.001
  - 1.
  rMC_th: !!python/tuple
  - 0.001
  - 1.
  rCM_th1: !!python/tuple
  - 0.001
  - 1.
  rCM_peak1: !!python/tuple
  - 0.001
  - 1.
  rCM_th2: !!python/tuple
  - 0.01
  - 1.
  rCM_peak2: !!python/tuple
  - 0.001
  - 1.
  rCM_min2: !!python/tuple
  - 0.01
  - 1.
  rMC0: !!python/tuple
  - 0.1
  - 10.
  rCM0: !!python/tuple
  - 0.1
  - 10.
  local_signal_rise: !!python/tuple
  - 5.
  - 200.
  local_signal_decay: !!python/tuple
  - 50.
  - 1500.
  global_signal_rise: !!python/tuple
  - 5.
  - 200.
  global_signal_decay: !!python/tuple
  - 100.
  - 3000.
  peak_delta_weight: !!python/tuple
  - 1.5
  - 4.
default_params:
rel_bounds:
- - local_signal_decay
  - '>'
  - 1.0
  - local_signal_rise
- - global_signal_decay
  - '>'
  - 1.0
  - global_signal_rise
- - local_signal_decay
  - '>'
  - 1.0
  - global_signal_decay
- - rMC_peak
  - '>'
  - 1.0
  - rMC_th
- - rCM_peak1
  - '>'
  - 1.0
  - rCM_th1
- - rCM_peak2
  - '>'
  - 1.0
  - rCM_th1
- - rCM_th2
  - '>'
  - 1.0
  - rCM_peak1
- - rCM_th2
  - '>'
  - 1.0
  - rCM_peak2
feature_names:
- induction1_peak_val
- induction1_peak_shift
- induction1_min_val
- induction1_ramp_width
- induction2_null_peak_val
- induction2_null_peak_shift
- induction2_null_min_val
- induction2_null_ramp_width
- induction2_shift_peak_val
- induction2_shift_peak_shift
- induction2_shift_delta_peak_val_initial
- induction2_shift_min_val
- induction2_shift_ramp_width
update_context:
- - optimize_BTSP_CA1_synthetic
  - update_model_params
get_features_stages:
- source: optimize_BTSP_CA1_synthetic
  get_args_static: get_args_static_model_ramp
  compute_features: compute_features_model_ramp
  filter_features: filter_features_model_ramp
get_objectives:
  optimize_BTSP_CA1_synthetic: get_objectives
kwargs:
  verbose: 1
  min_delta_weight: -0.2
  ramp_scaling_factor: 0.002956
  induction_locs:
    1: 130.
    2: 10.
  x_opt:
    global_signal_decay: 150.
    local_signal_rise: 6.362730E+01
    rMC0: 2.136997E+00
    rMC_th: 3.034372E-01
    rMC_peak: 7.292308E-01
    global_signal_rise: 1.051905E+01
    peak_delta_weight: 2.682327E+00
    rCM0: 1.306494E+00
    local_signal_decay: 8.652857E+02
    rCM_min2: 2.838575E-01
    rCM_th1: 7.639369E-02
    rCM_th2: 9.596845E-01
    rCM_peak1: 2.086415E-01
    rCM_peak2: 3.751629E-01
objective_names:
- induction1_ramp_residual_score
- induction2_null_ramp_residual_score
- induction2_shift_ramp_feature_score
optimization_title: bidirectional_BTSP_synthetic
param_gen: PopulationAnnealing
param_names:
- rMC_peak
- rMC_th
- rCM_th1
- rCM_peak1
- rCM_th2
- rCM_peak2
- rCM_min2
- rMC0
- rCM0
- local_signal_rise
- local_signal_decay
- global_signal_rise
- global_signal_decay
- peak_delta_weight
target_range:
  ramp_offset: 0.01
  peak_loc: 0.01
  peak_val: 0.01
  min_val: 0.01
  residuals: 0.1
  weights_smoothness: 0.01
  delta_min_val: 0.01
  delta_peak_val: 0.01
target_val:
  peak_shift_1: -10.
  peak_shift_2: 0.
  peak_val_1: 8.
  peak_val_2: 8.
  # min_val_2: 3.
  delta_peak_val_1: -4.
x0:
  global_signal_decay: 150.
  local_signal_rise: 6.362730E+01
  rMC0: 2.136997E+00
  rMC_th: 3.034372E-01
  rMC_peak: 7.292308E-01
  global_signal_rise: 1.051905E+01
  peak_delta_weight: 2.682327E+00
  rCM0: 1.306494E+00
  local_signal_decay: 8.652857E+02
  rCM_min2: 2.838575E-01
  rCM_th1: 7.639369E-02
  rCM_th2: 9.596845E-01
  rCM_peak1: 2.086415E-01
  rCM_peak2: 3.751629E-01
