bounds:
  spine_th_depo: !!python/tuple
  - 0.
  - 1.
  spine_th_hyper: !!python/tuple
  - 0.
  - 1.
  spine_th: !!python/tuple
  - 0.05
  - 1.
  spine_half_width: !!python/tuple
  - 0.05
  - 1.
  f_dep_th: !!python/tuple
  - 0.0001
  - 1.
  f_dep_half_width: !!python/tuple
  - 0.001
  - 1.
  k_pot: !!python/tuple
  - 0.01
  - 10.
  k_dep: !!python/tuple
  - 0.01
  - 10.
  local_signal_decay: !!python/tuple
  - 50.
  - 1500.
  global_signal_decay: !!python/tuple
  - 50.
  - 1500.
  peak_delta_weight: !!python/tuple
  - 1.5
  - 6.
default_params:
  # f_dep_half_width: 9.091255E-02
  # f_dep_th: 8.894545E-03
  global_signal_decay: 7.416242E+02
  # k_dep: 3.161347E-01
  # k_pot: 6.702605E-01
  local_signal_decay: 1.012450E+03
  # peak_delta_weight: 4.650342E+00
  spine_half_width: 4.077459E-01
  spine_th: 5.531024E-01
rel_bounds:
#- - local_signal_decay
#  - '>'
#  - 1.0
#  - global_signal_decay
#- - k_pot
#  - '>'
#  - 1.0
#  - k_dep
- - spine_th_hyper
  - '>'
  - 1.0
  - spine_th
- - spine_th_depo
  - '<'
  - 1.0
  - spine_th
feature_names:
- induction1_delta_val_at_target_peak
- induction1_delta_val_at_model_peak
- induction1_delta_width
- induction1_delta_peak_shift
- induction1_delta_asymmetry
- induction1_delta_min_loc
- induction1_delta_val_at_target_min
- induction1_delta_val_at_model_min
- induction1_depo_delta_val_at_target_peak
- induction1_depo_delta_val_at_model_peak
- induction1_depo_delta_width
- induction1_depo_delta_peak_shift
- induction1_depo_delta_asymmetry
- induction1_depo_delta_min_loc
- induction1_depo_delta_val_at_target_min
- induction1_depo_delta_val_at_model_min
- induction1_hyper_delta_val_at_target_peak
- induction1_hyper_delta_val_at_model_peak
- induction1_hyper_delta_width
- induction1_hyper_delta_peak_shift
- induction1_hyper_delta_asymmetry
- induction1_hyper_delta_min_loc
- induction1_hyper_delta_val_at_target_min
- induction1_hyper_delta_val_at_model_min
- induction2_delta_val_at_target_peak
- induction2_delta_val_at_model_peak
- induction2_delta_width
- induction2_delta_peak_shift
- induction2_delta_asymmetry
- induction2_delta_min_loc
- induction2_delta_val_at_target_min
- induction2_delta_val_at_model_min
- induction2_hyper_delta_val_at_target_peak
- induction2_hyper_delta_val_at_model_peak
- induction2_hyper_delta_width
- induction2_hyper_delta_peak_shift
- induction2_hyper_delta_asymmetry
- induction2_hyper_delta_min_loc
- induction2_hyper_delta_val_at_target_min
- induction2_hyper_delta_val_at_model_min
- ramp_amp_after_first_plateau
update_context:
- - optimize_biBTSP_synthetic_hybrid_norm
  - update_model_params
get_features_stages:
- source: optimize_biBTSP_synthetic_hybrid_norm
  get_args_static: get_args_static_model_ramp
  compute_features: compute_features_model_ramp
  filter_features: filter_features_model_ramp
get_objectives:
  optimize_biBTSP_synthetic_hybrid_norm: get_objectives
kwargs:
  data_file_name: 20201123_biBTSP_data.hdf5
  input_field_width: 90.  # cm
  verbose: 1
  num_induction_laps: 3
  min_delta_weight: -0.2
  max_dend_depo: 10.
  min_dend_depo: -20.
  default_run_vel: 25.
  induction_loc:
    '1': 120.
    '2': 45.
  target_ramp_width: 150.
  target_peak_delta_weight: 3.
  target_peak_shift_1: -5.
  target_peak_val_1: 8.
  target_peak_val_1_depo: 9.5
  target_peak_val_1_hyper: 6.
  target_ramp_offset_1_depo: 10.
  target_ramp_offset_1_hyper: -20.
  target_ramp_offset_2_hyper: -20.
  weights_path_distance_threshold: 1.25
objective_names:
- induction1_residual_score
- induction1_depo_residual_score
- induction1_hyper_residual_score
- induction2_residual_score
- induction2_hyper_residual_score
# - ramp_amp_after_first_plateau
- weights_path_distance
optimization_title: biBTSP_synthetic_hybrid_norm
param_gen: PopulationAnnealing
param_names:
- spine_th_depo
- spine_th_hyper
- spine_th
- spine_half_width
- f_dep_th
- f_dep_half_width
- k_pot
- k_dep
- local_signal_decay
- global_signal_decay
- peak_delta_weight
target_range:
  ramp_offset: 0.01
  delta_min_val: 0.01
  delta_peak_val: 0.01
  residuals: 0.1
  weights_smoothness: 0.015
  ramp_amp_after_first_plateau: 0.01
  weights_path_distance: 0.1
target_val:
  ramp_amp_after_first_plateau: 4.
x0:
  f_dep_half_width: 1.225082E-02
  f_dep_th: 5.874827E-03
  global_signal_decay: 7.416242E+02
  k_dep: 2.285727E-01
  k_pot: 2.406468E+00
  local_signal_decay: 1.012450E+03
  peak_delta_weight: 4.622392E+00
  spine_half_width: 4.077459E-01
  spine_th: 5.531024E-01
  spine_th_depo: 3.140178E-01
  spine_th_hyper: 8.621754E-01
