37:
  2:
    current_columns:
    - 0
    - 1
    - 2
    - 3
    - 4
    file_name: yl200203_close2.txt
    position_columns:
      induction:
      - 5
      - 6
      - 7
      - 8
      - 9
    ramp_columns:
      after: 12
      before: 10
    sampling_rate: 1000.0
    spont: False
44:
  3:
    current_columns:
    - 7
    - 8
    file_name: yl200206_close2.txt
    position_columns:
      induction:
      - 5
      - 6
    ramp_columns:
      after: 3
      before: 2
    sampling_rate: 1000.0
    spont: False
45:
  2:
    current_columns:
    - 7
    - 8
    file_name: yl200212_far2.txt
    position_columns:
      induction:
      - 5
      - 6
    ramp_columns:
      after: 2
      before: 3
    sampling_rate: 1000.0
    spont: False
46:
  2:
    current_columns:
    - 9
    - 10
    - 11
    - 12
    file_name: yl200217_far2.txt
    position_columns:
      induction:
      - 5
      - 6
      - 7
      - 8
    ramp_columns:
      after: 2
      before: 3
    sampling_rate: 1000.0
    spont: False
47:
  2:
    current_columns:
    - 7
    - 8
    file_name: yl200219_far2.txt
    position_columns:
      induction:
      - 5
      - 6
    ramp_columns:
      after: 3
      before: 2
    sampling_rate: 1000.0
    spont: False
  3:
    current_columns:
    - 13
    - 14
    file_name: yl200219_far2.txt
    position_columns:
      induction:
      - 11
      - 12
    ramp_columns:
      after: 9
      before: 3
    sampling_rate: 1000.0
    spont: False
48:
  2:
    current_columns:
    - 6
    file_name: yl200309_close2.txt
    position_columns:
      induction:
      - 5
    ramp_columns:
      after: 3
      before: 2
    sampling_rate: 1000.0
    spont: False
  3:
    current_columns:
    - 6
    file_name: yl200309_far2.txt
    position_columns:
      induction:
      - 5
    ramp_columns:
      after: 3
      before: 2
    sampling_rate: 1000.0
    spont: False
50:
  2:
    current_columns:
      - 11
      - 10
      - 9
      - 8
      - 7
    file_name: kb150619_1.txt
    position_columns:
      induction:
        - 6
        - 5
        - 4
        - 3
        - 12
    ramp_columns:
      after: 1
      before: 0
    sampling_rate: 1000.0
    spont: False
51:
  2:
    current_columns:
      - 4
      - 5
    file_name: yl200320_1.txt
    position_columns:
      induction:
        - 2
        - 3
    ramp_columns:
      after: 7
      before: 6
    sampling_rate: 1000.0
    spont: False
  3:
    current_columns:
      - 6
    file_name: yl200320_2.txt
    position_columns:
      induction:
        - 4
      post:
        - 5
    ramp_columns:
      after: 3
      before: 2
    sampling_rate: 1000.0
    spont: False
52:
  2:
    current_columns:
      - 4
      - 5
    file_name: yl200321_2.txt
    position_columns:
      induction:
        - 6
        - 7
    ramp_columns:
      after: 3
      before: 2
    sampling_rate: 1000.0
    spont: False
53:
  2:
    current_columns:
      - 4
      - 6
    file_name: yl200305_1.txt
    position_columns:
      induction:
        - 3
        - 5
    ramp_columns:
      after: 2
      before: 1
    sampling_rate: 1000.0
    spont: False