1:
  1:
    current_columns:
    - 4
    - 5
    - 6
    - 7
    file_name: 151006_3i_1.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
      - 3
    ramp_columns:
      after: 8
    sampling_rate: 1000.0
    spont: False
  2:
    current_columns:
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    file_name: 151006_4ii.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      pre:
      - 8
    ramp_columns:
      after: 18
      before: 17
    sampling_rate: 20000.0
    spont: False
2:
  1:
    current_columns:
    - 5
    - 6
    - 7
    - 8
    - 9
    file_name: 160204_2i.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
      - 3
      - 4
    ramp_columns:
      after: 10
    sampling_rate: 1000.0
    spont: False
3:
  1:
    current_columns:
    - 1
    file_name: 130925s.txt
    position_columns:
      induction:
      - 0
    ramp_columns:
      after: 2
    sampling_rate: 20000.0
    spont: True
4:
  1:
    current_columns:
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    file_name: 160323_2i.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
    ramp_columns:
      after: 14
    sampling_rate: 1000.0
    spont: False
  2:
    current_columns:
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    file_name: 160323_2ii.txt
    position_columns:
      pre:
      - 0
      induction:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
    ramp_columns:
      before: 13
      after: 14
    sampling_rate: 20000.0
    spont: False
5:
  1:
    current_columns:
    - 5
    - 6
    - 7
    - 8
    - 9
    file_name: 160310_4i.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
      - 3
      - 4
    ramp_columns:
      after: 10
    sampling_rate: 1000.0
    spont: False
  2:
    current_columns:
    - 6
    - 7
    - 8
    - 9
    - 10
    file_name: 160310_4ii.txt
    position_columns:
      pre:
      - 0
      induction:
      - 1
      - 2
      - 3
      - 4
      - 5
    ramp_columns:
      before: 11
      after: 12
    sampling_rate: 20000.0
    spont: False
6:
  1:
    current_columns:
    - 7
    - 8
    - 9
    - 10
    - 11
    file_name: 150422.txt
    position_columns:
      pre:
      - 0
      induction:
      - 1
      - 2
      - 3
      - 4
      - 5
    ramp_columns:
      after: 6
    sampling_rate: 1000.0
    spont: False
7:
  1:
    current_columns:
    - 7
    - 8
    - 9
    - 10
    - 11
    file_name: 151203.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
      - 3
      - 4
    ramp_columns:
      before: 5
      after: 6
    sampling_rate: 1000.0
    spont: False
  2:
    current_columns:
    - 6
    - 7
    - 8
    - 9
    - 10
    file_name: 151203_4ii.txt
    position_columns:
      pre:
      - 5
      induction:
      - 0
      - 1
      - 2
      - 3
      - 4
    ramp_columns:
      before: 12
      after: 13
    sampling_rate: 20000.0
    spont: False
9:
  1:
    current_columns:
    - 6
    - 7
    - 8
    - 9
    - 10
    file_name: 160309.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
      - 3
      - 4
    ramp_columns:
      after: 5
    sampling_rate: 1000.0
    spont: False
  2:
    current_columns:
    - 7
    - 8
    - 9
    - 10
    - 11
    file_name: 160309_2ii.txt
    position_columns:
      pre:
      - 0
      induction:
      - 1
      - 2
      - 3
      - 4
      - 5
      post:
      - 6
    ramp_columns:
      before: 13
      after: 14
    sampling_rate: 20000.0
    spont: False
10:
  1:
    current_columns:
    - 8
    - 9
    - 10
    - 11
    - 12
    file_name: 160721.txt
    position_columns:
      pre:
      - 0
      induction:
      - 1
      - 2
      - 3
      - 4
      - 5
    ramp_columns:
      before: 6
      after: 7
    sampling_rate: 1000.0
    spont: False
11:
  2:
    current_columns:
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    file_name: 160826_2ii_star.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    ramp_columns:
      before: 12
      after: 13
    sampling_rate: 20000.0
    spont: False
12:
  1:
    current_columns:
    - 0
    - 1
    - 2
    file_name: 140522_3i.txt
    position_columns:
      induction:
      - 3
      - 4
      - 5
    ramp_columns:
      after: 6
    sampling_rate: 1000.0
    spont: False
13:
  1:
    current_columns:
    - 3
    - 4
    - 5
    file_name: 140529_6i.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
    ramp_columns:
      after: 6
    sampling_rate: 1000.0
    spont: False
14:
  1:
    current_columns:
    - 0
    - 1
    - 2
    - 3
    - 4
    file_name: 140609_4i.txt
    position_columns:
      induction:
      - 5
      - 6
      - 7
      - 8
      - 9
    ramp_columns:
      after: 10
    sampling_rate: 1000.0
    spont: False
15:
  1:
    current_columns:
    - 5
    - 6
    - 7
    - 8
    - 9
    file_name: 151007_2i.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
      - 3
      - 4
    ramp_columns:
      after: 10
    sampling_rate: 1000.0
    spont: False
  2:
    current_columns:
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    file_name: 151007_2ii.txt
    position_columns:
      pre:
      - 0
      induction:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
    ramp_columns:
      before: 14
      after: 15
    sampling_rate: 20000.0
    spont: False
16:
  1:
    current_columns:
    - 1
    file_name: 131210s.txt
    position_columns:
      induction:
      - 0
    ramp_columns:
      after: 2
    sampling_rate: 20000.0
    spont: True
17:
  1:
    current_columns:
    - 5
    - 6
    - 7
    - 8
    - 9
    file_name: 160308_2i.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
      - 3
      - 4
    ramp_columns:
      after: 10
    sampling_rate: 1000.0
    spont: False
18:
  1:
    current_columns:
    - 5
    - 6
    - 7
    - 8
    - 9
    file_name: 160318_2i.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
      - 3
      - 4
    ramp_columns:
      after: 10
    sampling_rate: 1000.0
    spont: False
  2:
    current_columns:
    - 6
    - 7
    - 8
    - 9
    - 10
    file_name: 160318_2ii_star.txt
    position_columns:
      pre:
      - 5
      induction:
      - 0
      - 1
      - 2
      - 3
      - 4
    ramp_columns:
      before: 11
      after: 12
    sampling_rate: 20000.0
    spont: False
19:
  1:
    current_columns:
    - 5
    - 6
    - 7
    - 8
    - 9
    file_name: 140516_3i.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
      - 3
      - 4
    ramp_columns:
      after: 10
    sampling_rate: 1000.0
    spont: False
20:
  1:
    current_columns:
    - 5
    - 6
    - 7
    - 8
    - 9
    file_name: 140520_4i.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
      - 3
      - 4
    ramp_columns:
      after: 10
    sampling_rate: 1000.0
    spont: False
21:
  1:
    current_columns:
    - 3
    - 4
    - 5
    file_name: 140926_1i.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
    ramp_columns:
      after: 6
    sampling_rate: 1000.0
    spont: False
22:
  1:
    current_columns:
    - 0
    - 1
    - 2
    - 3
    file_name: 150413i.txt
    position_columns:
      induction:
      - 4
      - 5
      - 6
      - 7
    ramp_columns:
      after: 8
    sampling_rate: 1000.0
    spont: False
23:
  1:
    current_columns:
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    file_name: 151013_6i.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    ramp_columns:
      after: 12
    sampling_rate: 1000.0
    spont: False
24:
  1:
    current_columns:
    - 2
    file_name: 140330s.txt
    position_columns:
      pre:
      - 0
      induction:
      - 1
    ramp_columns:
      after: 3
    sampling_rate: 20000.0
    spont: True
25:
  1:
    current_columns:
    - 1
    file_name: 140411s.txt
    position_columns:
      induction:
      - 0
    ramp_columns:
      after: 2
    sampling_rate: 20000.0
    spont: True
26:
  1:
    current_columns:
    - 2
    file_name: 140730s.txt
    position_columns:
      pre:
      - 0
      induction:
      - 1
    ramp_columns:
      after: 3
    sampling_rate: 20000.0
    spont: True
27:
  1:
    current_columns:
    - 2
    file_name: 141221s.txt
    position_columns:
      pre:
      - 0
      induction:
      - 1
    ramp_columns:
      after: 3
    sampling_rate: 20000.0
    spont: True
29:
  2:
    current_columns:
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    file_name: 150604ni.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    ramp_columns:
      before: 12
      after: 13
    sampling_rate: 20000.0
    spont: False
30:
  2:
    current_columns:
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    file_name: 150625ni.txt
    position_columns:
      induction:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    ramp_columns:
      before: 12
      after: 13
    sampling_rate: 20000.0
    spont: False
31:
  2:
    current_columns:
    - 6
    - 7
    - 8
    - 9
    - 10
    file_name: 150827ni.txt
    position_columns:
      pre:
      - 0
      induction:
      - 1
      - 2
      - 3
      - 4
      - 5
    ramp_columns:
      before: 11
      after: 12
    sampling_rate: 20000.0
    spont: False
28:
  2:
    current_columns:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    file_name: 151009_1ni.txt
    position_columns:
      induction:
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
    ramp_columns:
      before: 12
      after: 13
    sampling_rate: 20000.0
    spont: False
37:
  2:
    current_columns:
    - 0
    - 1
    - 2
    - 3
    - 4
    file_name: yl200203_close2.txt
    position_columns:
      induction:
      - 5
      - 6
      - 7
      - 8
      - 9
    ramp_columns:
      after: 12
      before: 10
    sampling_rate: 1000.0
    spont: False
44:
  3:
    current_columns:
    - 7
    - 8
    file_name: yl200206_close2.txt
    position_columns:
      induction:
      - 5
      - 6
    ramp_columns:
      after: 3
      before: 2
    sampling_rate: 1000.0
    spont: False
45:
  2:
    current_columns:
    - 7
    - 8
    file_name: yl200212_far2.txt
    position_columns:
      induction:
      - 5
      - 6
    ramp_columns:
      after: 2
      before: 3
    sampling_rate: 1000.0
    spont: False
46:
  2:
    current_columns:
    - 9
    - 10
    - 11
    - 12
    file_name: yl200217_far2.txt
    position_columns:
      induction:
      - 5
      - 6
      - 7
      - 8
    ramp_columns:
      after: 2
      before: 3
    sampling_rate: 1000.0
    spont: False
47:
  2:
    current_columns:
    - 7
    - 8
    file_name: yl200219_far2.txt
    position_columns:
      induction:
      - 5
      - 6
    ramp_columns:
      after: 3
      before: 2
    sampling_rate: 1000.0
    spont: False
  3:
    current_columns:
    - 13
    - 14
    file_name: yl200219_far2.txt
    position_columns:
      induction:
      - 11
      - 12
    ramp_columns:
      after: 9
      before: 3
    sampling_rate: 1000.0
    spont: False
48:
  2:
    current_columns:
    - 6
    file_name: yl200309_close2.txt
    position_columns:
      induction:
      - 5
    ramp_columns:
      after: 3
      before: 2
    sampling_rate: 1000.0
    spont: False
  3:
    current_columns:
    - 6
    file_name: yl200309_far2.txt
    position_columns:
      induction:
      - 5
    ramp_columns:
      after: 3
      before: 2
    sampling_rate: 1000.0
    spont: False
50:
  2:
    current_columns:
      - 11
      - 10
      - 9
      - 8
      - 7
    file_name: kb150619_1.txt
    position_columns:
      induction:
        - 6
        - 5
        - 4
        - 3
        - 12
    ramp_columns:
      after: 1
      before: 0
    sampling_rate: 1000.0
    spont: False
51:
  2:
    current_columns:
      - 4
      - 5
    file_name: yl200320_1.txt
    position_columns:
      induction:
        - 2
        - 3
    ramp_columns:
      after: 7
      before: 6
    sampling_rate: 1000.0
    spont: False
  3:
    current_columns:
      - 6
    file_name: yl200320_2.txt
    position_columns:
      induction:
        - 4
      post:
        - 5
    ramp_columns:
      after: 3
      before: 2
    sampling_rate: 1000.0
    spont: False
52:
  2:
    current_columns:
      - 4
      - 5
    file_name: yl200321_2.txt
    position_columns:
      induction:
        - 6
        - 7
    ramp_columns:
      after: 3
      before: 2
    sampling_rate: 1000.0
    spont: False
53:
  2:
    current_columns:
      - 4
      - 6
    file_name: yl200305_1.txt
    position_columns:
      induction:
        - 3
        - 5
    ramp_columns:
      after: 2
      before: 1
    sampling_rate: 1000.0
    spont: False