data_file_name: 20190711_biBTSP_data_calibrated_input.hdf5
input_field_width: 90.  # cm
min_delta_weight: -0.2
initial_ramp_peak_val: 8.
target_peak_shift: -10.
num_cells: 1000
initial_fraction_active: 0.
basal_target_representation_density: 0.3
reward_target_representation_density: 0.45
track_phases:
  - lap_type: explore
    label: 'novel explore'
    num_laps: 10
    color: 'c'
  - lap_type: reward
    label: 'fixed reward'
    reward_loc: 90.
    num_laps: 10
    color: 'r'
  - lap_type: explore
    label: 'familiar explore'
    num_laps: 5
    color: 'k'
peak_basal_plateau_prob_per_lap: 0.05
peak_reward_plateau_prob_per_lap: 0.05
basal_plateau_prob_ramp_sensitivity: 0.
reward_plateau_prob_ramp_sensitivity: 2.
seed_offset: 90000000000
trial: 0
target_range:
  ramp_offset: 0.01
  delta_min_val: 0.01
  delta_peak_val: 0.01
  residuals: 0.1
  weights_smoothness: 0.005
x0:
  f_dep_peak: 1.194999E-01
  f_dep_th: 7.820899E-03
  f_pot_peak: 9.828062E-01
  f_pot_th: 5.262555E-01
  global_signal_decay: 2.232987E+02
  global_signal_rise: 3.183521E+01
  k_dep: 3.498200E-01
  k_pot: 1.172080E+00
  local_signal_decay: 1.127795E+03
  local_signal_rise: 1.597686E+02
  peak_delta_weight: 2.400251E+00
