input_field_width: 90.  # cm
verbose: 1
num_induction_laps: 3
min_delta_weight: -0.2
max_dend_depo: 10.
default_run_vel: 25.
default_track_length: 187.
default_num_inputs: 200
expand_track: 4
induction_loc:
  '1': 320.
  '2': 235.
target_ramp_width_1: 160.
target_ramp_pot_width_2: 160.
target_ramp_dep_width_2: 140.
target_peak_delta_weight: 3.
target_peak_shift: -12.5
target_peak_val_1: 8.
target_asymmetry_1: 2.2
target_asymmetry_2: 2.5
target_pot_delta_peak_val_2: 7.65
target_dep_delta_peak_val_2: -5.
weights_path_distance_threshold: 1.25
param_names:
- f_pot_th
- f_pot_half_width
- f_dep_th
- f_dep_half_width
- k_pot
- k_dep
- local_signal_decay
- global_signal_decay
- peak_delta_weight
target_range:
  ramp_offset: 0.01
  delta_min_val: 0.01
  delta_peak_val: 0.01
  residuals: 0.1
  weights_smoothness: 0.015
  ramp_amp_after_first_plateau: 0.01
  weights_path_distance: 0.1
target_val:
  ramp_amp_after_first_plateau: 4.
x0:
  f_dep_half_width: 1.166108E-02
  f_dep_th: 1.026429E-03
  f_pot_half_width: 2.967520E-01
  f_pot_th: 3.871166E-02
  global_signal_decay: 5.973286E+02
  k_dep: 2.896611E-01
  k_pot: 1.573373E+00
  local_signal_decay: 1.447838E+03
  peak_delta_weight: 3.620245E+00
