data_file_name: 20200527_biBTSP_data.hdf5
input_field_width: 90.  # cm
min_delta_weight: -0.2
initial_ramp_peak_val: 8.
target_peak_shift: -10.
target_ramp_width: 150.
default_run_vel: 25.
num_cells: 500
initial_fraction_active: 0.
basal_target_representation_density: 0.5
reward_target_representation_density: 1.
track_phases:
  - lap_type: explore
    label: 'novel explore'
    num_laps: 10
    color: 'c'
  - lap_type: reward
    label: 'fixed reward'
    reward_loc: 90.
    num_laps: 10
    color: 'r'
  - lap_type: explore
    label: 'familiar explore'
    num_laps: 5
    color: 'k'
peak_basal_plateau_prob_per_sec: 0.0075
peak_reward_plateau_prob_per_sec: 0.04
basal_plateau_prob_ramp_sensitivity: 0.
reward_plateau_prob_ramp_sensitivity: 2.
seed_offset: 90000000000
trial: 0
target_range:
  ramp_offset: 0.01
  delta_min_val: 0.01
  delta_peak_val: 0.01
  residuals: 0.1
  weights_smoothness: 0.015
x0:
  # f_dep_half_width: 8.100359E-02
  # f_dep_th: 1.279724E-02
  # global_signal_decay: 7.826026E+02
  # k_dep: 2.088454E-01
  # k_pot: 4.893109E-01
  # local_signal_decay: 1.075317E+03
  # peak_delta_weight: 4.392292E+00
  f_dep_half_width: 9.187833E-02
  f_dep_th: 2.164153E-03
  global_signal_decay: 7.084890E+02
  k_dep: 2.423430E-01
  k_pot: 5.690617E-01
  local_signal_decay: 1.112847E+03
  peak_delta_weight: 4.447377E+00